Release 3.0.7

diff --git a/scripts/bootstrap b/scripts/bootstrap
--- a/scripts/bootstrap
+++ b/scripts/bootstrap
@@ -7,21 +7,23 @@ set -ev
 
 cd "$(dirname "$0")/.."
 
-hash brew 2>/dev/null || {
-  echo >&2 "The command 'brew' is required but not installed. See https://brew.sh for installation guidelines.";
-  exit 1;
-}
+if [ -f "Brewfile" ] && [ "$(uname -s)" = "Darwin" ]; then
+  hash brew 2>/dev/null || {
+    echo >&2 "The command 'brew' is required but not installed. See https://brew.sh for installation guidelines.";
+    exit 1;
+  }
 
-brew bundle check >/dev/null 2>&1  || {
-  echo "==> Installing Homebrew dependencies…"
-  brew bundle
-}
+  brew bundle check >/dev/null 2>&1  || {
+    echo "==> Installing Homebrew dependencies…"
+    brew bundle
+  }
+fi
 
-mint bootstrap
-
-hash bundle 2>/dev/null || {
-  echo "==> Installing Bundler 2.1.4…"
-  gem install bundler -v 2.1.4 --no-document --quiet
-}
-echo "==> Installing gem dependencies…"
-bundle install --system
+if [ -f "Gemfile" ]; then
+  hash bundle 2>/dev/null || {
+    echo "==> Installing Bundler 2.1.4…"
+    gem install bundler -v 2.1.4 --no-document --quiet
+  }
+  echo "==> Installing gem dependencies…"
+  bundle install --system
+fi
